info:
  project:
    name: mint-ecommerce

server:
  port: 8080

spring:
  application:
    name: mint-ecommerce

  # Checar se a url precisa de mudança ao conteniarizar o banco
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5432/menta-ecommerce
    username: mint_ecommerce_app
    password: mint-ecommerce-app-pw

  cache:
    type: redis

  redis:
    host: redis-mint-ecommerce
    port: 6379

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  metrics:
    enable:
      jvm: true
    export:
      prometheus:
        enabled: true
    distribution:
      sla:
        http:
          server:
            requests: [50ms, 100ms, 200ms, 300ms]
    tags:
      application: mint-ecommerce
